[workspace]
members = [
    "chacha20",
    "hc-256",
    "rabbit",
    "salsa20",
]

[patch.crates-io]
cipher = { git = "https://github.com/RustCrypto/traits/", branch = "cipher_v0.4" }
inout = { git = "https://github.com/RustCrypto/utils", branch = "add_inout" }
